# Generated by Django 4.2.1 on 2023-05-24 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sanskrit_name', models.CharField(max_length=50)),
                ('english_name', models.CharField(max_length=50)),
                ('img_url', models.URLField(max_length=250)),
                ('peak', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Yogi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(max_length=150)),
                ('isInstructor', models.BooleanField(default=False)),
                ('userPhoto', models.URLField(max_length=250)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('difficulty', models.IntegerField()),
                ('poseColumnIdList', models.ManyToManyField(related_name='flow', to='fyfapi.pose')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_flows', to='fyfapi.yogi')),
            ],
        ),
    ]
